@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(player, "Player", "A user of Project StarDust, with a user account")
System_Ext(spatial_world, "SpatialOS World", "A persistent way to store gamedata")
System_Ext(playfab, "PlayFab", "Stores all player-relative informations")


System_Boundary(stardust_client, "StarDust Client") {
    Container(unity_client, "UnityClient Worker", "Unity 2019.7.3f1", "Manage client connections with SpatialOS and client logic")
}


Rel(player, stardust_client, "Plays")

Rel(unity_client, spatial_world, "Exchange data with")
Rel(unity_client, playfab, "Login with")
@enduml
